import Link from 'next/link'
import './globals.css'

// title
export const metadata = {
  title: 'Create bible',
  description: 'Generated by create bible',
  icons:{
    icon:'/images/gumy.jpg'
  }
}

export default function RootLayout({ children }) {
  return (
    <html >
      <body >
        <h1><Link href='/'>WEB</Link></h1>
        <ol>
          <li><a href='read/1'>HTML</a></li>
          <li><a href='read/2'>CSS</a></li>
          <li><a href='read/3'>JS</a></li>
        </ol>
        {children}
        <ul>
          <li><a href='/create'>Create</a></li>
          <li><a href='/update/1'>Update</a></li>
          <li><input type='button' value="delete" /></li>

        </ul>
        </body>
    </html>
  )
}
